let article_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task8%20i.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task8%20ii.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task8%20ii..jpg?raw=true","2014T8"]
let article_second = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0015.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0016.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0017.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0030.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0031.jpg?raw=true","2015T10"]
let article_third = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_3.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_4.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_9.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_10.jpg?raw=true","2017T9"]
let article_fouth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_4.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_5.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_11.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_12.jpg?raw=true","2019T9"]
let article_fiveth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0010.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0011.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0014.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0022.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0023.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0026.jpg?raw=true","2012T9"]
let article_sixth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0012.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0013.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0014.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0024.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0025.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0026.jpg?raw=true","2012T10"]
let article_seventh = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task8.jpg?raw=true","2013T8"]
let article_eighth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10..jpg?raw=true","2013T10"]

let report_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_1.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_2.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_7.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_8.jpg?raw=true","2017T8"]
let report_second = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_1.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_2.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_5.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_6.jpg?raw=true","2018T8"]
let report_third = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_1.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_2.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_3.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_8.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_9.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_10.jpg?raw=true","2019T8"]
let report_fouth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9%20tbc.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9..jpg?raw=true","2020T9"]

let letter_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10%20i.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10%20i..jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10%20ii.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10..jpg?raw=true","2014T10"]
let letter_second = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_5.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_6.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_11.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2017-Sample-ENG-Paper3_12.jpg?raw=true","2017T10"]
let letter_third = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2021%20(1).jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2021%20(5).jpg?raw=true","2021T9"]

let email_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9.jpg?raw=true","2013T9"]
let email_second = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_1.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_2.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_7.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_7.jpg?raw=true","2016T8"]
let email_third = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10%20tbc.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task10..jpg?raw=true","2020T10"]
let email_fouth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_3.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_4.jpg?raw=true", "https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_9.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_10.jpg?raw=true","2022T9"]
let email_fiveth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0011.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0012.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0026.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0027.jpg?raw=true","2015T8"]
let email_sixth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0013.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0014.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0028.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2015-DSE-ENG-LANG-3-Sample_page-0029.jpg?raw=true","2015T9"]
let email_seventh = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_4.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_9.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_10.jpg?raw=true","2018T10"]
let email_eighth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_3.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_7.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2018-Sample-ENG-Paper3_8.jpg?raw=true","2018T9"]
let email_nineth = ["https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2021%20(5).jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2021%20(6).jpg","2021T8"]
let email_tenth = ["https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2021%20(3).jpg","2021T10"]
let email_eleventh = ["https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0013.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0014.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0027.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0028.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0041.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0042.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0054.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0055.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0068.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0069.jpg",
"2023T9"]

let mainbody_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0009.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0014.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0021.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2012%20HKDSE%20English%20Language%20Exemplars_pages-to-jpg-0026.jpg?raw=true","2012T8"]
let mainbody_second = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_1.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_2.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_7.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_8.jpg?raw=true","2022T8"]
let mainbody_third = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_3.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_4.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_9.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_10.jpg?raw=true","2016T9"]
let mainbody_fourth = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_5.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_6.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_11.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2016-Sample-ENG-Paper3_12.jpg?raw=true","2016T10"]

let announcement = ["https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0011.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0012.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0025.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0026.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0038.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0039.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0040.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0052.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0053.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0066.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0067.jpg",
"2023T8"]

let speech_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9%20i.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9%20i..jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9%20ii.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task9%20ii..jpg?raw=true","2014T9"]
let speech_second = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_6.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_7.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_13.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_14.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2019-Sample-ENG-Paper3_15.jpg?raw=true","2019T10"]
let speech_third = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_5.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_6.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_11.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_12.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_23.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/2022-Sample-ENG-Paper3_24.jpg?raw=true","2022T10"]

let script_first = ["https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task8%20tbc.jpg?raw=true","https://github.com/nutureSelection/dse_listening_task.github.io/blob/main/task8..jpg?raw=true","2020T8"]
let script_second = ["https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0015.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0016.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0029.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0043.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0056.jpg","https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0057.jpg",
"https://raw.githubusercontent.com/nutureSelection/dse_listening_task.github.io/main/2023-Sample-ENG-Paper3_page-0070.jpg",
"2023T10"]
